# 1. Find the inverse of the following matrix M.                                                        2. Find the determinant and the eigen values of the above matrix.                         3. Using Matrix inversion, solve the following system of equations                         4. Plot x^2 + y^2 = 25                                                                                                     5. Plot z = sin x + sin y using imshow from -4pi to 4pi for both x and y.   

In [3]:
import numpy as np
A=np.array([[1,4,4,1],[0,1,-2,2],[3,3,1,4],[0,1,-3,-2]])
A

array([[ 1,  4,  4,  1],
       [ 0,  1, -2,  2],
       [ 3,  3,  1,  4],
       [ 0,  1, -3, -2]])

In [5]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.22222222, -0.51851852,  0.40740741,  0.18518519],
       [ 0.22222222,  0.18518519, -0.07407407,  0.14814815],
       [ 0.08888889, -0.12592593, -0.02962963, -0.14074074],
       [-0.02222222,  0.28148148,  0.00740741, -0.21481481]])

In [6]:
A_det = np.linalg.det(A)
A_det

135.00000000000003

In [7]:
E=np.matrix([[1,4,4,1],[0,1,-2,2],[3,3,1,4],[0,1,-3,-2]])
eigvals=np.linalg.eigvals(E)
print(eigvals)

[ 2.731601+3.2150887j   2.731601-3.2150887j  -2.231601+1.61396767j
 -2.231601-1.61396767j]


In [9]:
F=np.array([[3,-1,2],[2,1,-1],[1,3,-5]])
F_inv=np.linalg.inv(F)
F_inv

array([[ 0.4, -0.2,  0.2],
       [-1.8,  3.4, -1.4],
       [-1. ,  2. , -1. ]])

In [11]:
import matplotlib.pyplot as plt  
def gra(formula, x_range, y_range, z_range):  
    x = np.array(x_range)  
    y = eval(formula)
    plt.plot(x, y)  
    plt.show()
    
gra(x**2+y**2+z**2=25,10,20,30)

SyntaxError: keyword can't be an expression (<ipython-input-11-dc02a7e9dfee>, line 8)